export default {
	SET_GRAPH: 'SET_GRAPH',
	SELECT_NODE: 'SELECT_NODE',
	DESELECT_NODE: 'DESELECT_NODE',
	SET_NODE_POS: 'SET_NODE_POS',
	NEW_CONNECTOR: 'NEW_CONNECTOR',
	REMOVE_CONNECTOR: 'REMOVE_CONNECTOR',
	ADD_NEW_NODE: 'ADD_NEW_NODE',
	UPDATE_NODE: 'UPDATE_NODE',
	DELETE_NODE: 'DELETE_NODE',
	SET_STATE: 'SET_STATE',
	MOVE_ALL_NODES: 'MOVE_ALL_NODES',

	SET_VIEW: 'SET_VIEW'
}

