export default {
	SET_GRAPH: 'SET_GRAPH',
	SELECT_NODE: 'SELECT_NODE',
	DESELECT_NODE: 'DESELECT_NODE',
	SET_NODE_POS: 'SET_NODE_POS',
	NEW_CONNECTOR: 'NEW_CONNECTOR',
	REMOVE_CONNECTOR: 'REMOVE_CONNECTOR',
}

